services:

  # Single-printer:    MODE=reg docker compose up
  # Three-printer:     MODE=max docker compose up
  # Local dev:         DEV_MODE=true docker compose up
  server:
    build:
      context: ./app
    ports:
      - "8080:8080"
    environment:
      - DEV_MODE=${DEV_MODE:-false}
      - MODE=${MODE:-reg}
    volumes:
      - ./app/.env.1:/app/.env.1:ro
      - ./app/.env.2:/app/.env.2:ro
      - ./app/.env.3:/app/.env.3:ro
    restart: unless-stopped
